name: diff3f
channels:
  # - pytorch3d
  - fvcore
  - iopath
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - matplotlib=3.7.1
  - numpy=1.25.0
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - meshplot
  - pytorch=2.4.1
  - sam-2
  # - pytorch3d
  - torchvision
  - fvcore
  - iopath
  - notebook
  # - xformers==0.0.21
  - pip:
    - accelerate==0.21.0
    - diffusers==0.21.4
    - einops==0.7.0
    - huggingface-hub==0.17.3
    - meshio==5.3.4
    - meshplot
    - opencv-python==4.8.1.78
    - plyfile==1.0.1
    # - torch==2.4.1
    # - torchvision
    - transformers==4.34.1
    - trimesh==4.0.0
    - potpourri3d==1.0.0
    - robust_laplacian==0.2.7

  # then do:
  # find $CONDA_PREFIX -name "*torch_python*"
  # export LIBRARY_PATH=$CONDA_PREFIX/lib:$LIBRARY_PATH
  # export LDFLAGS="-L$CONDA_PREFIX/lib $LDFLAGS"
  # MACOSX_DEPLOYMENT_TARGET=10.14 CC=clang CXX=clang++ pip install "git+https://github.com/facebookresearch/pytorch3d.git"
  # git clone https://github.com/facebookresearch/sam2
  # mv sam2 sam2_download
  # cd sam2_download
  # SAM2_BUILD_CUDA=0 pip install -e